MODELS = [
    [
        "{x} at lower frequencies, specifically between 3Hz and 5Hz",
        "{x} in the lower frequency band, specifically from 3Hz to 5Hz",
        "{x} within the 3Hz to 5Hz frequency window",
        "{x} between 3Hz and 5Hz",
        "{x} in the 3Hz to 5Hz range",
        "{x} in the low-frequency range of 3Hz to 5Hz",
    ],
    [
        "{x} within the frequency range of 5Hz to 19Hz",
        "{x} in the frequency interval from 5Hz to 19Hz",
        "{x} spanning the 5Hz to 19Hz range",
        "{x} in the 5Hz-19Hz frequency band",
        "{x} across the 5Hz to 19Hz range",
        "{x} between 5Hz and 19Hz",
        "{x} from 5Hz to 19Hz",
    ],
    [
        "{x} at the first harmonic",
        "{x} at the first harmonic frequency",
        "{x} at the frequency of the first harmonic",
    ],
    [
        "{x} around the first harmonic",
        "{x} in the vicinity of the first harmonic",
        "{x} near the first harmonic",
        "{x} close to the first harmonic",
        "{x} just around the first harmonic",
        "{x} in the region surrounding the first harmonic",
        "{x} in the area near the first harmonic",
        "{x} in frequencies adjacent to the first harmonic",
        "{x} in close proximity to the first harmonic",
    ],
    [
        "{x} at the second harmonic",
        "{x} at the second harmonic frequency",
        "{x} at the frequency of the second harmonic",
    ],
]


FEATURES = [
    [
        [
            "little to no noise",
            "insignificant or no noise",
            "no noticeable noise",
            "little to no detectable noise",
            "barely any noticeable noise",
            "minimal noise presence",
            "almost no surrounding noise",
            "almost no perceptible noise",
            "negligible noise",
            "hardly any noise",
        ],
        [
            "some small noise",
            "a small amount of noise",
            "a slight amount of noise",
            "little noise",
            "a bit of noise",
            "low-level noise",
            "a modest amount of noise",
            "a faint presence of noise",
            "a small degree of noise",
            "some low-intensity noise",
        ],
        [
            "some considerable noise",
            "relevant noise",
            "noisy tendencies",
            "a noticeable amount of noise",
            "moderate to high noise levels",
            "a fair amount of noise",
            "non-negligible noise",
            "a certain degree of noise",
            "a marked presence of noise",
        ],
        [
            "considerable noise",
            "distracting noise",
            "an uncommon noise",
            "a disruptive noise",
            "a confusing noise",
            "an intrusive noise",
            "a signal-masking noise",
            "a noise that affects clarity",
            "a visually distracting noise",
        ],
    ],
    [
        [
            "no exponential behavior",
            "an absence of exponential behavior",
            "no sign of exponential behavior",
            "a lack of exponential characteristics",
            "no evidence of exponential pattern",
            "no indication of exponential trend",
            "no exponential response detected",
            "an absence of exponential dynamics",
            "no exponential-like behavior present",
        ],
        [
            "some small exponential behavior",
            "an exponential curve",
            "an exponential drop",
            "a slight exponential behavior",
            "a mild exponential trend",
            "a weak exponential pattern",
            "a subtle exponential response",
            "a low-level exponential behavior",
            "a minimally exponential tendency",
            "a faint exponential progression",
            "a modest exponential dynamic",
            "a gently exponential behavior",
            "a small-scale exponential trend",
        ],
        [
            "a greatly exponential behavior",
            "a big exponential curve",
            "a heavily exponential drop",
            "a steep exponential decline",
            "a sharp exponential drop",
            "a significant exponential decrease",
            "a rapid exponential fall",
            "a dramatic exponential reduction",
            "a strongly exponential decay",
            "a heavily sloped exponential drop",
            "a fast-falling exponential trend",
            "a pronounced exponential descent",
            "an intense exponential drop-off",
        ],
    ],
    [
        [
            "no peak",
            "no noticeable peak",
            "no visible peak",
            "no apparent peak",
            "no significant peak",
            "no identifiable peak",
            "no discernible peak",
            "an absence of a detectable peak",
            "no peak structure",
        ],
        [
            "a low peak",
            "a small peak",
            "a minor peak",
            "a subtle peak",
            "a slight peak",
            "a faint peak",
            "a weak peak",
            "a modest peak",
            "a low-amplitude peak",
            "a less prominent peak",
        ],
        [
            "a medium-sized peak",
            "a moderate peak",
            "a mid-sized peak",
            "a peak of medium amplitude",
            "a reasonably sized peak",
            "a peak of average height",
            "a peak with moderate intensity",
            "a peak of intermediate size",
        ],
        [
            "a great peak",
            "a high peak",
            "a prominent peak",
            "a strong peak",
            "a large peak",
            "a tall peak",
            "a peak with high amplitude",
            "a pronounced peak",
            "a clearly dominant peak",
            "a significant peak",
            "a major peak",
        ],
    ],
    [
        [
            "no noticeable noise",
            "little to no detectable noise",
            "barely any noticeable noise",
            "minimal noise presence",
            "almost no surrounding noise",
            "almost no perceptible noise",
            "negligible noise",
            "hardly any noise",
        ],
        [
            "noisy behavior",
            "high noise levels",
            "significant noise",
            "noticeable noise activity",
            "pronounced noise patterns",
            "strong noise presence",
            "marked noise behavior",
            "considerable noise fluctuations",
            "evident noise interference",
            "substantial noise",
        ],
    ],
    [
        [
            "a low peak",
            "a small peak",
            "a minor peak",
            "a subtle peak",
            "a slight peak",
            "a faint peak",
            "a weak peak",
            "a modest peak",
            "a low-amplitude peak",
            "a less prominent peak",
        ],
        [
            "a great peak",
            "a high peak",
            "a prominent peak",
            "a strong peak",
            "a large peak",
            "a tall peak",
            "a peak with high amplitude",
            "a pronounced peak",
            "a clearly dominant peak",
            "a significant peak",
            "a major peak",
        ],
    ],
]
